# Generated by Django 2.2.7 on 2019-11-28 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
                ('nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=128)),
                ('descripcion', models.CharField(max_length=512)),
                ('created', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.CharField(max_length=512)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=2)),
                ('precioNeto', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indicaciones', models.CharField(max_length=128)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('especializacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Especialidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('informe', models.CharField(max_length=1024)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dentista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Paciente')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alergia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Paciente')),
            ],
        ),
    ]
