# Generated by Django 2.2.7 on 2019-11-28 03:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentista',
            name='is_dentist',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
