# Generated by Django 2.2.7 on 2019-11-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191127_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=models.TextField(max_length=1024),
        ),
    ]
