# Generated by Django 2.2.7 on 2019-11-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191127_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
