# Generated by Django 2.2.7 on 2019-11-30 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191128_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='informe',
            field=models.CharField(default='No se ha agregado informe.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tratamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tratamiento'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='precioNeto',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
