# Generated by Django 2.2.7 on 2019-11-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191130_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='precioNeto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
