# Generated by Django 2.2.7 on 2019-12-01 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191201_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tratamiento'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Categoria'),
            preserve_default=False,
        ),
    ]
