# Generated by Django 2.2.7 on 2019-12-01 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191201_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
