# Generated by Django 2.2.7 on 2019-12-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191201_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promo/%Y/%m/%D/'),
        ),
    ]
