# Generated by Django 2.2.7 on 2019-12-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_promocion_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
