# Generated by Django 2.2.7 on 2019-12-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_promocion_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/%Y/%m/%D/'),
        ),
    ]
