# Generated by Django 2.2.7 on 2019-12-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tratamiento_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='correo',
        ),
        migrations.AddField(
            model_name='dentista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='services/%Y/%m/%D/'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='patient/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dentist/%Y/%m/%D/'),
        ),
    ]
