# Generated by Django 2.2.7 on 2019-12-02 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20191201_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentista',
            name='correo',
        ),
    ]
