# Generated by Django 2.2.7 on 2019-12-02 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_dentista_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentista',
            old_name='especializacion',
            new_name='especialidad',
        ),
    ]
