# Generated by Django 2.2.7 on 2019-12-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20191201_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentista',
            name='biografia',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
