# Generated by Django 2.2.7 on 2019-12-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_dentista_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='dentist/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/%Y/%m/%D/'),
        ),
    ]
