# Generated by Django 2.2.7 on 2019-12-02 19:33

import core.models
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_paciente_alergias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200, null=True, verbose_name=core.models.Medicamento),
        ),
    ]
