# Generated by Django 2.2.7 on 2019-12-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20191202_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='alergias',
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.ManyToManyField(blank=True, null=True, to='core.Medicamento'),
        ),
    ]
