# Generated by Django 2.2.7 on 2019-12-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20191202_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=models.ManyToManyField(blank=True, to='core.Medicamento'),
        ),
    ]
