# Generated by Django 2.2.7 on 2019-12-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20191202_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alergia',
        ),
    ]
