# Generated by Django 2.2.7 on 2019-12-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20191202_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentista',
            name='telefono',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=8),
        ),
    ]
