# Generated by Django 2.2.7 on 2019-12-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20191203_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
