# Generated by Django 2.2.7 on 2019-12-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20191203_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
