# Generated by Django 2.2.7 on 2019-12-04 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20191203_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Dentista'),
        ),
    ]
