# Generated by Django 2.2.7 on 2019-12-18 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_paciente_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentista',
            name='id',
        ),
        migrations.AlterField(
            model_name='dentista',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
